config/routes.rb
Rails.application.routes.draw do
  # A user can see the list of cocktails
  resources :cocktails, only: [:index, :new, :create] do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true

  validates :ingredient, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.eager_load(doses: :ingredient).all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      # redirect_to cocktail_path(cocktail)
      redirect_to cocktails_path
    else
      render :new
    end
  end


  private
  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @ingredients = Ingredient.all
    @cocktail    = Cocktail.find(params[:cocktail_id])
    @dose        = Dose.new
  end

  def create
    @dose     = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])

    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktails_path
    else
      @ingredients = Ingredient.all
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy

    redirect_to cocktails_path
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1>All cocktails</h1>


<%= link_to "Add a cocktail", new_cocktail_path, class:"btn btn-primary" %>
<!-- <ul>
  <li>
    Mojito
    <ul>
      <li>5cl - rum</li>
      <li>5cl - rum</li>
    </ul>
  </li>
  <li>Gin fizz</li>
</ul>
 -->

<ul>
  <% @cocktails.each do |cocktail| %>
    <li>
      <h3><%= cocktail.name %> - <%= link_to 'Add a dose', new_cocktail_dose_path(cocktail) %></h3>
      <ul>
        <% cocktail.doses.each do |dose| %>
          <li>
            <%= dose.description %> - <%= dose.ingredient.name %>
            <%= link_to 'Delete dose', dose_path(dose), method: :delete %>
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

app/views/cocktails/new.html.erb
<h1>Create a new cocktail</h1>

<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>

  <%= f.button :submit %>
<% end %>

app/views/doses/new.html.erb
<h1>Add a dose to <%= @cocktail.name %> cocktail!</h1>

<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.input :description %>
  <%# f.association :ingredient %>

  <%= f.input :ingredient_id, collection: @ingredients %>

  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>